# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jubarbie <jubarbie@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/10/30 16:51:35 by jubarbie          #+#    #+#              #
#    Updated: 2016/02/18 11:55:42 by jubarbie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC=gcc
CFLAGS=-I Includes -Wall -Wextra -Werror
SRC=	Sources/main.c \
		Sources/ft_atoi.c \
		Sources/map.c \
		Sources/box.c \
		Sources/tab.c \
		Sources/bsq.c \
		Sources/map_print.c \
		Sources/ft_putstr.c
OBJ=$(SRC:.c=.o)
NAME=bsq

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) -o $@ $^
	
%.o: %.c
	$(CC) -o $@ -c $< $(CFLAGS)

clean:
	rm -rf $(OBJ)

fclean: clean
	rm -rf $(NAME)

re: fclean all
